### ISSUE TITLE
trouble if more than one ssh-agent is running?

### ISSUE THREAD

**Issue by tinker2much** [gitbls/rxapp#1]
t2m@MacBook-Air ~ % env | grep SSH
SSH_AUTH_SOCK=/var/folders/vy/fj6vc ... 0000gn/T//ssh-jAyhS8sXOpTe/agent.2351
SSH_AGENT_PID=2352

t2m@MacBook-Air ~ % rxapp pi@pi42.local xeyes
? Your ssh-agent isn't running case 2

t2m@MacBook-Air bin % pgrep -U $(id -u) ssh-agent
1784
2096
2352
Press any key to continue...                                                                                                                             

so tail works in this case, but the desired one might not always be the last one:

t2m@MacBook-Air bin % [ "$(pgrep -U $(id -u) ssh-agent | tail -n 1)" != "$SSH_AGENT_PID" ] && echo "? Your ssh-agent isn't running 2"
Press any key to continue...

**Comment by gitbls** [comment]
OK, I'll bite (or byte, as the case may be). Why do you have 3 ssh-agents running? If you're using ssh-agent properly you'll have exactly one running per user.

In the README it shows, for using `keychain`
```
    # keystart and keystop aliases make it easy to stop and restart ssh-agent
    # Replace 'sshkeyfile' with the filename(s) of the keys you want to use (just the filename, not full path)
    alias keystart='keychain -q --nogui [--ignore-missing] --agents ssh sshkeyfile1 sshkeyfile2 ; source ~/.keychain/$(hostname)-sh'
    alias keystop='keychain -q --stop all'  # Use keystop to stop the running ssh-agent (it's ok to not stop it)
    keystart                                # If your private keys have passwords, you will be prompted to enter them
                                            # The optional `--ignore-missing` switch eliminates messages about missing keys.
```
And if you're simply using `ssh-agent` by itself
```
eval `ssh-agent`    # Start ssh-agent
ssh-add sshkeyfile  # Add the private key identity to ssh-agent
 (For example  ssh-add ~/.ssh/id_rsa)
```
Inquiring minds want to know: Which are you using, and why do you have all those ssh-agents running?

**Comment by gitbls** [comment]
OK, I just tried the eval ssh-agent and answered my own question. Best approach for you is to use `keychain`, or alternatively, add code to whatever you're using to start ssh-agent to not do so if one is already running. Either approach is fine. Adding code to rxapp for this doesn't seem like the correct answer to me.

I'll update the doc for this to explain how to ensure there's only one running. keychain is the easiest, otherwise you'll need to add more code to not start redundant ssh-agents.

**Comment by tinker2much** [comment]
I have different terminal sessions open on the Mac, doing different things. One might be using screen to connect to a dozen pi's. One might be connecting to single random pi's as needed. One might be hitting my git repositories. The ssh-agent in one terminal session does not enable passwordless ssh in another terminal session. The only way I've found to do that is when I login to a full pi installation that's currently set to boot to the console - if I do ssh-agent at the console, then do startx, I've found that ANY terminal session or process in the GUI already partakes in that agent. 


On Sunday, October 29, 2023 at 04:21:07 PM CDT, Benn ***@***.***> wrote: 







OK, I'll bite (or byte, as the case may be). Why do you have 3 ssh-agents running? If you're using ssh-agent properly you'll have exactly one running per user.

In the README it shows, for using keychain
    # keystart and keystop aliases make it easy to stop and restart ssh-agent
    # Replace 'sshkeyfile' with the filename(s) of the keys you want to use (just the filename, not full path)
    alias keystart='keychain -q --nogui [--ignore-missing] --agents ssh sshkeyfile1 sshkeyfile2 ; source ~/.keychain/$(hostname)-sh'
    alias keystop='keychain -q --stop all'  # Use keystop to stop the running ssh-agent (it's ok to not stop it)
    keystart                                # If your private keys have passwords, you will be prompted to enter them
                                            # The optional `--ignore-missing` switch eliminates messages about missing keys.

And if you're simply using ssh-agent by itself
eval `ssh-agent`    # Start ssh-agent
ssh-add sshkeyfile  # Add the private key identity to ssh-agent
(For example  ssh-add ~/.ssh/id_rsa)

Inquiring minds want to know: Which are you using, and why do you have all those ssh-agents running?

**Comment by gitbls** [comment]
It's not clear to me why you wouldn't want to have all keys available in all sessions, but different strokes for different folks, and this is Linux after all. 😁

Try the updated version I just posted and LMK if it works better for you. Thx!

**Comment by tinker2much** [comment]
FYI: at least in the GUI on a pi5 running wayland, there's already an instance of ssh-agent running, before the user does anything:

pi@pi5:~ $ pgrep -U $(id -u) ssh-agent
1539
pi@pi5:~ $ ps -fade | grep ssh-agent | grep -v grep
pi          1539    1465  0 14:11 ?        00:00:00 /usr/bin/ssh-agent /usr/bin/wayfire-pi

**Comment by tinker2much** [comment]
Using the updated version, trying to run "rxapp pi8.local xvkbd", I see a flash of the app (a virtual keyboard app), then it goes away.

**Comment by gitbls** [comment]
> Using the updated version, trying to run "rxapp pi8.local xvkbd", I see a flash of the app (a virtual keyboard app), then it goes away.

I just fired up xvkbd on a Pi0W and it displayed correctly, so I'm going to need more information to sort out what's going on.
* Do other xapps work correctly if you try to start them on this combination systems? Is it just xvkbd or is it all xapps?
* What model Pi and OS are the app-starting Pi?
* What model Pi and OS are the app-running Pi (where xvkbd runs)?
* How many ssh-agents are running on the app-starting pi? 
* Which one of the ssh-agents has the key for the app-running Pi? (What is it's position (m) in list of N ssh-agents?)
* Is there anything useful in any of these logfiles
  * journalctl
    *  First line of interest: `Accepted publickey for <username> from <ipaddr> port 52052 ssh2: blarg blarg`
    * Last line of interest: `Removed slice user-<uid>.slice - User Slice of UID <uid>`

**Comment by tinker2much** [comment]
> It's not clear to me why you wouldn't want to have all keys available in all sessions, but different strokes for different folks, and this is Linux after all. 😁
> 
> Try the updated version I just posted and LMK if it works better for you. Thx!

Admitting ignorance: I actually would want to have all keys available to all sessions, but I habitually start ssh-agent like "ssh-agent bash" or "ssh-agent zsh". This is not reasoned, informed behavior, but a complete habit formed decades ago (and based on minimal knowledge then too). Am I to understand that all I have to do is start ssh-agent like you propose, and it would be available to any and every terminal session or app I start after that point?

**Comment by tinker2much** [comment]
I tried starting ssh-agent the eval way as above, and it works in that terminal session (IE, I can do an "ssh localhost" and I'm not asked for a password). If I open another terminal session, it's not active there, as shown by being asked for a password if I do "ssh localhost".

???

**Comment by tinker2much** [comment]
I just fired up xvkbd on a Pi0W and it displayed correctly, so I'm going to need more information to sort out what's going on.

Do other xapps work correctly if you try to start them on this combination systems? Is it just xvkbd or is it all xapps?
    I just installed x11-apps on the target machine so I have more choices:
    xkkbd still does not work, but xclock and xlogo and xcalc and even chromium-browser do...
What model Pi and OS are the app-starting Pi?
    pi5 8GB, bookworm 64
What model Pi and OS are the app-running Pi (where xvkbd runs)?
    pi4 8GB, bullseye 64
How many ssh-agents are running on the app-starting pi?
    two - the one that seems to always be started, and the one I started via eval
    pi@pi5:~ $ ps -fade | grep ssh-agent | grep -v grep
    pi          1496    1421  0 02:25 ?        00:00:00 /usr/bin/ssh-agent /usr/bin/wayfire-pi
    pi          4388       1  0 02:36 ?        00:00:00 ssh-agent

Which one of the ssh-agents has the key for the app-running Pi? (What is it's position (m) in list of N ssh-agents?)
    pi@pi5:~/bin $ pgrep -U $(id -u) ssh-agent
    1496
    4388

Is there anything useful in any of these logfiles
journalctl
First line of interest: Accepted publickey for <username> from <ipaddr> port 52052 ssh2: blarg blarg
Last line of interest: Removed slice user-<uid>.slice - User Slice of UID <uid>

This is all so far:
Nov 02 02:36:43 pi5 sshd[4416]: Accepted publickey for pi from ::1 port 42758 ssh2: RSA SHA256:0N9XKHGrroDbxUBJQ+gvzzotcs39r18r4R50+uwSm7Y
Nov 02 02:36:43 pi5 sshd[4416]: pam_unix(sshd:session): session opened for user pi(uid=1000) by (uid=0)
Nov 02 02:36:43 pi5 systemd-logind[782]: New session 4 of user pi.
Nov 02 02:36:43 pi5 systemd[1]: Started session-4.scope - Session 4 of User pi.
Nov 02 02:36:43 pi5 sshd[4416]: pam_env(sshd:session): deprecated reading of user environment enabled
Nov 02 02:36:45 pi5 sshd[4422]: Received disconnect from ::1 port 42758:11: disconnected by user
Nov 02 02:36:45 pi5 sshd[4422]: Disconnected from user pi ::1 port 42758
Nov 02 02:36:45 pi5 systemd[1]: session-4.scope: Deactivated successfully.
Nov 02 02:36:45 pi5 sshd[4416]: pam_unix(sshd:session): session closed for user pi
Nov 02 02:36:45 pi5 systemd-logind[782]: Session 4 logged out. Waiting for processes to exit.
Nov 02 02:36:45 pi5 systemd-logind[782]: Removed session 4.
Nov 02 02:37:04 pi5 sshd[4465]: Connection closed by authenticating user pi ::1 port 53732 [preauth]
Nov 02 02:40:49 pi5 systemd[1]: Starting systemd-tmpfiles-clean.service - Cleanup of Temporary Directories...
Nov 02 02:40:49 pi5 systemd[1]: systemd-tmpfiles-clean.service: Deactivated successfully.
Nov 02 02:40:49 pi5 systemd[1]: Finished systemd-tmpfiles-clean.service - Cleanup of Temporary Directories.
Nov 02 02:40:49 pi5 systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dclean.service.mount: Deactivated successfully.

**Comment by gitbls** [comment]
I don't understand why you're having problems with xvkbd, but if other apps start correctly using rxapp then the issue with with xvkbd, and not a generic problem with rxapp. If you run into a problematic app you'll have to use your amazing problem-solving skills (like the ones you demonstrated with the broken Disk ID) to solve it.

As far as using ssh-agent, and getting all your ssh keys available in all terminal sessions, you have two choices:
* Figure out how to identify whether you have an existing ssh-agent running and use it if it exists. If it doesn't, then and only then, start one
* Use `keychain`, which does all of that for you

I booted up a Bookworm system with Desktop and indeed, there was already an ssh-agent running. I used my standard `keystart` command (which is documented in the rxapp README as well as in the `rxapp` file itself), and PRESTO! keychain found the running ssh-agent and added my keys to it.

So, only one ssh-agent running, and as a VERY COOL bonus, when running on Bookworm Desktop, terminal sessions automatically inherit the existing ssh-agent session. I started a second terminal window and was able to ssh to another host with no password prompt.

I hope the above convinces you to spend 10 minutes to add keychain to your repertoire. Simply:
* Install it on your current system for testing (and then, of course, in sdm)
* Add the suggested definitions for `keystart` and `keystop` to your .bashrc, modifying them as appropriate for the names of your ssh keys
* When you create a new terminal window, simply type `keystart`. If there's no ssh-agent running, or if the running ssh-agent doesn't have the keys loaded into it, it will prompt for the passwords for your keys (if any). If there's an ssh-agent running already, this session will be enabled to use it.
* And, as I previously mentioned, on Bookworm Desktop you don't even need to type `keystart` in terminal windows after the first one, they inherit it automatically. That said, it doesn't cause any issues if you type it again.

Finally, if `keychain` isn't installable on your MacBook, you can simply copy the file /bin/keychain from RasPiOS and place it in your path on the Mac, so you can use keychain there as well.

**Comment by tinker2much** [comment]
All I need to do on bookworm/wayland is "ssh-add" the first time I start a terminal, and it works as you described, active in that or any later terminal session. I'm accustomed to using the bare ssh-agent / ssh-add commands so I'll keep doing that, only now with only the ONE command. Splendid!

Given that xvkbd was just a randomly chosen X application to test rxapp, there's no need for further worry about it, now that I know so many others work. Which is good, because my problem solving skills are a little tired at the moment.

And rxapp is very nice, thank you.

**Comment by tinker2much** [comment]
I created an FYI kind of post about this on the raspberry pi forum: [https://forums.raspberrypi.com/viewtopic.php?t=358852](url)

**Comment by gitbls** [comment]
Nice.

**Comment by gitbls** [comment]
> All I need to do on bookworm/wayland is "ssh-add" the first time I start a terminal, and it works as you described, active in that or any later terminal session. I'm accustomed to using the bare ssh-agent / ssh-add commands so I'll keep doing that, only now with only the ONE command. Splendid!
> 
> Given that xvkbd was just a randomly chosen X application to test rxapp, there's no need for further worry about it, now that I know so many others work. Which is good, because my problem solving skills are a little tired at the moment.
> 
> And rxapp is very nice, thank you.

Perfect!
